import { Check, Megaphone, Send, Sparkles, X } from "lucide-react";
import type { Recommendation } from "../types";

const money = (paise?: number) => paise === undefined ? "—" : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(paise / 100);

export function CampaignsPage({ campaigns, loading, onGenerate, onApprove, onReject }: { campaigns: Recommendation[]; loading: boolean; onGenerate: () => Promise<void>; onApprove: (id: number, proposedPricePaise?: number) => Promise<void>; onReject: (id: number) => Promise<void> }) {
  return <div className="space-y-7"><section className="rounded-2xl border border-sky-200 bg-white p-7 shadow-sm sm:p-9"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-sky-600">Campaign control center</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Approve campaign drafts before they go live.</h2><p className="mt-3 max-w-2xl text-slate-500">Campaign Agent turns catalog and inventory signals into explainable commercial drafts. Arvya never sends or publishes a campaign automatically.</p></div><button onClick={() => void onGenerate()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg bg-sky-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-sky-700 disabled:opacity-60"><Sparkles size={17} /> {loading ? "Drafting…" : "Generate campaign drafts"}</button></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Guardrail label="Drafted by agent" detail="Evidence and copy are recorded" /><Guardrail label="Merchant approval" detail="Required before customer visibility" /><Guardrail label="No auto-send" detail="Channel execution stays under control" /></div></section>{campaigns.length ? <div className="grid gap-5 xl:grid-cols-2">{campaigns.map((campaign) => <CampaignCard key={campaign.id} campaign={campaign} loading={loading} onApprove={onApprove} onReject={onReject} />)}</div> : <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><Megaphone className="mx-auto text-sky-600" /><h3 className="mt-4 font-semibold">No campaign drafts yet</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Run the Growth Agent to identify an in-stock product with a healthy contribution margin and create a reviewable campaign draft.</p></section>}</div>;
}

function CampaignCard({ campaign, loading, onApprove, onReject }: { campaign: Recommendation; loading: boolean; onApprove: (id: number, proposedPricePaise?: number) => Promise<void>; onReject: (id: number) => Promise<void> }) {
  const signals = campaign.evidence_json.signals ?? [];
  const featured = String(campaign.evidence_json.featured_product ?? "Featured catalog product");
  const copy = String(campaign.action_payload_json.campaign_copy ?? "Campaign copy will be drafted after analysis.");
  const statusStyle = campaign.status === "approved" ? "bg-emerald-50 text-emerald-700" : campaign.status === "rejected" ? "bg-slate-100 text-slate-600" : "bg-amber-50 text-amber-700";
  return <article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-sky-50 text-sky-600"><Megaphone size={20} /></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${statusStyle}`}>{campaign.status.replace("_", " ")}</span></div><p className="mt-5 text-xs font-semibold uppercase tracking-[.16em] text-sky-600">Campaign draft</p><h3 className="mt-2 text-xl font-semibold text-slate-900">{campaign.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{campaign.rationale}</p><section className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">Draft copy</p><p className="mt-2 text-sm leading-6 italic text-slate-700">“{copy}”</p></section><div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Featured product" value={featured} /><Metric label="Offer price" value={money(campaign.action_payload_json.proposed_price_paise)} /><Metric label="Est. uplift" value={`₹${campaign.impact_json.estimated_monthly_revenue_uplift_inr.toLocaleString("en-IN")}`} /></div><section className="mt-5"><p className="text-sm font-medium text-slate-800">Why this draft exists</p><div className="mt-2 flex flex-wrap gap-2">{signals.map((signal) => <span key={signal} className="rounded-full bg-sky-50 px-2.5 py-1 text-xs text-sky-700">{signal}</span>)}</div></section>{campaign.status === "pending_approval" && <div className="mt-6 flex flex-wrap gap-3"><button disabled={loading} onClick={() => void onApprove(campaign.id)} className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-600 px-3.5 py-2 text-sm font-medium text-white hover:bg-emerald-700 disabled:opacity-50"><Check size={16} /> Approve draft</button><button disabled={loading} onClick={() => void onReject(campaign.id)} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3.5 py-2 text-sm font-medium text-slate-600 hover:bg-slate-50 disabled:opacity-50"><X size={16} /> Reject</button></div>}{campaign.status === "approved" && <p className="mt-6 inline-flex items-center gap-2 text-sm font-medium text-emerald-700"><Check size={16} /> Merchant approved — ready for controlled channel execution.</p>}{campaign.status === "rejected" && <p className="mt-6 text-sm text-slate-500">Merchant rejected this draft; no campaign action was taken.</p>}</article>;
}

function Guardrail({ label, detail }: { label: string; detail: string }) { return <div className="rounded-xl border border-sky-100 bg-sky-50/60 p-3"><div className="flex items-center gap-2 text-sm font-medium text-sky-800"><Send size={15} /> {label}</div><p className="mt-1 text-xs text-sky-700">{detail}</p></div>; }

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-3"><p className="text-[11px] font-medium uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 truncate text-sm font-semibold text-slate-800" title={value}>{value}</p></div>; }
