import { Boxes, CircleAlert, IndianRupee, Layers3, Sparkles } from "lucide-react";
import type { AuditLog, CatalogSummary, Merchant } from "../types";
import { MetricCard } from "../components/dashboard/MetricCard";

const formatINR = (paise: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(paise / 100);

export function DashboardPage({ merchant, summary, activity, onOpenCatalog }: { merchant: Merchant; summary: CatalogSummary; activity: AuditLog[]; onOpenCatalog: () => void }) {
  return <div className="space-y-8"><section className="rounded-3xl border border-violet-400/20 bg-gradient-to-br from-violet-500/20 via-slate-900 to-slate-900 p-7 sm:p-9"><p className="text-sm font-medium text-violet-200">Merchant intelligence workspace</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Your catalog is ready for growth analysis.</h2><p className="mt-3 max-w-2xl text-slate-300">Arvya has established a clean product foundation for {merchant.name}. Next, its Growth Agent will identify approved bundle and upsell opportunities.</p><button onClick={onOpenCatalog} className="mt-6 rounded-lg bg-white px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-violet-100">Review catalog</button></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Catalog products" value={summary.total_products} detail={`${summary.active_products} active products`} icon={<Boxes size={19} />} /><MetricCard label="Categories mapped" value={summary.categories} detail="Ready for product clustering" icon={<Layers3 size={19} />} /><MetricCard label="Average price" value={formatINR(summary.average_price_paise)} detail="Catalog price baseline" icon={<IndianRupee size={19} />} /><MetricCard label="Data warnings" value={summary.missing_cost_data + summary.out_of_stock} detail={`${summary.missing_cost_data} missing cost · ${summary.out_of_stock} out of stock`} icon={<CircleAlert size={19} />} /></section><section className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-white/10 bg-slate-900/80 p-6"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Growth Agent</h2><p className="mt-1 text-sm text-slate-400">Day 2 capability</p></div><Sparkles className="text-violet-300" /></div><div className="mt-7 rounded-xl border border-dashed border-violet-400/30 bg-violet-500/5 p-5"><p className="font-medium">Catalog analysis is queued as the next step.</p><p className="mt-2 text-sm leading-6 text-slate-400">The agent will identify complementary products, validate margins and stock, then propose explainable merchant-approved offers.</p><button disabled className="mt-5 rounded-lg bg-slate-700 px-4 py-2 text-sm text-slate-400">Generate growth opportunities — Day 2</button></div></article><article className="rounded-2xl border border-white/10 bg-slate-900/80 p-6"><h2 className="font-semibold">Recent activity</h2><div className="mt-4 space-y-4">{activity.length ? activity.map((item) => <div key={item.id} className="border-l border-violet-400/40 pl-4"><p className="text-sm text-slate-200">{item.detail}</p><p className="mt-1 text-xs text-slate-500">{new Date(item.created_at).toLocaleString()}</p></div>) : <p className="text-sm text-slate-500">No activity yet.</p>}</div></article></section></div>;
}

