import { ExternalLink, RefreshCw, ShieldCheck } from "lucide-react";
import type { PaymentLink } from "../types";

const money = (paise: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(paise / 100);

export function PaymentLinksPage({ links, loading, onRetry }: { links: PaymentLink[]; loading: boolean; onRetry: (id: number) => Promise<void> }) {
  return <div className="space-y-7"><section><p className="text-sm font-semibold uppercase tracking-[.18em] text-sky-600">Payment operations</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Payment links and verified outcomes</h2><p className="mt-2 max-w-2xl text-slate-500">Razorpay creates the link; signed webhooks reconcile the final payment status in Arvya.</p></section><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h3 className="font-semibold">Checkout ledger</h3><p className="mt-1 text-xs text-slate-500">Idempotent link creation protects customers from duplicate requests.</p></div><ShieldCheck className="text-sky-600" size={20} /></div>{links.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Coupon</th><th className="px-5 py-3">Provider</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Created</th><th className="px-5 py-3">Action</th></tr></thead><tbody>{links.map((link) => <tr key={link.id} className="border-t border-slate-100"><td className="px-5 py-4 text-slate-700">{link.customer_email}</td><td className="px-5 py-4 font-medium text-slate-900">{money(link.amount_paise)}</td><td className="px-5 py-4 text-slate-500">{link.coupon_code ?? "—"}</td><td className="px-5 py-4 capitalize text-slate-600">{link.provider}</td><td className="px-5 py-4"><Status status={link.status} /></td><td className="px-5 py-4 text-slate-500">{new Date(link.created_at).toLocaleString()}</td><td className="px-5 py-4">{link.short_url ? <a href={link.short_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-sky-600 hover:text-sky-800">Open <ExternalLink size={14} /></a> : link.status === "execution_failed" || link.status === "demo_created" ? <button disabled={loading} onClick={() => void onRetry(link.id)} className="inline-flex items-center gap-1 text-sky-600 hover:text-sky-800 disabled:opacity-50"><RefreshCw size={14} /> Retry</button> : "—"}</td></tr>)}</tbody></table></div> : <div className="p-10 text-center text-sm text-slate-500">No payment links have been created yet.</div>}</section></div>;
}

function Status({ status }: { status: string }) { const styles: Record<string, string> = { paid: "bg-emerald-50 text-emerald-700", created: "bg-sky-50 text-sky-700", issued: "bg-sky-50 text-sky-700", execution_failed: "bg-rose-50 text-rose-700", demo_created: "bg-amber-50 text-amber-700", cancelled: "bg-slate-100 text-slate-600" }; return <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${styles[status] ?? "bg-slate-100 text-slate-600"}`}>{status.replace("_", " ")}</span>; }
