import { ArrowRight, BadgeIndianRupee, CheckCircle2, ExternalLink, Search, Sparkles, Ticket } from "lucide-react";
import { useState } from "react";
import type { PaymentLink, ShoppingOffer, ShoppingSearchResponse } from "../types";

const money = (paise: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(paise / 100);

export function ShoppingPage({ result, searching, error, onSearch, onCheckout }: { result: ShoppingSearchResponse | null; searching: boolean; error: string | null; onSearch: (query: string, budget: string) => Promise<void>; onCheckout: (offer: ShoppingOffer, name: string, email: string) => Promise<PaymentLink | undefined> }) {
  const [query, setQuery] = useState("skincare routine with sunscreen");
  const [budget, setBudget] = useState("1500");
  const [customerName, setCustomerName] = useState("Demo Customer");
  const [customerEmail, setCustomerEmail] = useState("customer@example.com");
  const [payment, setPayment] = useState<PaymentLink | null>(null);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setPayment(null); await onSearch(query, budget); };
  const checkout = async (offer: ShoppingOffer) => { const next = await onCheckout(offer, customerName, customerEmail); if (next) setPayment(next); };
  return <div className="space-y-7"><section className="rounded-3xl border border-cyan-400/20 bg-gradient-to-br from-cyan-500/15 via-slate-900 to-slate-900 p-7 sm:p-9"><p className="text-sm font-semibold uppercase tracking-[.18em] text-cyan-200">Customer Shopping Agent</p><h2 className="mt-2 max-w-3xl text-3xl font-semibold tracking-tight">Find the best merchant-approved offer—without hidden discounts or invented prices.</h2><p className="mt-3 max-w-3xl text-slate-300">Arvya compares only offers that a merchant has reviewed and approved, then applies eligible merchant-approved coupons before checkout.</p><form onSubmit={submit} className="mt-6 grid gap-3 lg:grid-cols-[1fr_150px_auto]"><label className="sr-only" htmlFor="shopping-query">What are you looking for?</label><div className="relative"><Search size={17} className="absolute left-3 top-3 text-slate-500" /><input id="shopping-query" value={query} onChange={(event) => setQuery(event.target.value)} className="w-full rounded-lg border border-white/15 bg-slate-950 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-cyan-300" placeholder="e.g. a skincare routine under ₹1,500" /></div><input value={budget} onChange={(event) => setBudget(event.target.value)} type="number" min="1" className="rounded-lg border border-white/15 bg-slate-950 px-3 py-2.5 text-sm outline-none focus:border-cyan-300" placeholder="Budget in ₹" /><button disabled={searching} className="rounded-lg bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-cyan-200 disabled:opacity-60">{searching ? "Comparing…" : "Compare offers"}</button></form></section>{error && <div className="rounded-xl border border-rose-400/20 bg-rose-400/10 p-4 text-sm text-rose-200">{error}</div>}{payment && <PaymentResult payment={payment} />}{result && <><section className="rounded-xl border border-white/10 bg-slate-900/70 p-4 text-sm text-slate-400"><span className="font-medium text-slate-200">Agent reasoning:</span> {result.recommendation_summary}</section>{result.offers.length ? <div className="grid gap-5 xl:grid-cols-2">{result.offers.map((offer, index) => <OfferCard key={offer.recommendation_id} offer={offer} rank={index + 1} customerName={customerName} customerEmail={customerEmail} onCustomerName={setCustomerName} onCustomerEmail={setCustomerEmail} onCheckout={checkout} disabled={searching} />)}</div> : <div className="rounded-2xl border border-dashed border-cyan-400/30 bg-cyan-500/5 p-10 text-center"><Sparkles className="mx-auto text-cyan-200" /><h3 className="mt-4 font-medium">No approved offers to compare yet</h3><p className="mt-2 text-sm text-slate-400">Open a merchant workspace, generate an opportunity, and approve it. It will then become eligible for this customer agent.</p></div>}</>}</div>;
}

function OfferCard({ offer, rank, customerName, customerEmail, onCustomerName, onCustomerEmail, onCheckout, disabled }: { offer: ShoppingOffer; rank: number; customerName: string; customerEmail: string; onCustomerName: (value: string) => void; onCustomerEmail: (value: string) => void; onCheckout: (offer: ShoppingOffer) => Promise<void>; disabled: boolean }) {
  return <article className={`rounded-2xl border bg-slate-900/80 p-6 ${rank === 1 ? "border-cyan-300/50" : "border-white/10"}`}><div className="flex items-start justify-between gap-4"><div>{rank === 1 && <span className="rounded-full bg-cyan-300/15 px-2.5 py-1 text-xs font-medium text-cyan-100">Best match</span>}<h3 className="mt-3 text-lg font-semibold">{offer.title}</h3><p className="mt-1 text-sm text-slate-400">{offer.merchant_name} · {offer.merchant_industry}</p></div><div className="text-right"><p className="text-xs text-slate-500">Final price</p><p className="text-xl font-semibold">{money(offer.final_price_paise)}</p></div></div><p className="mt-4 text-sm leading-6 text-slate-400">{offer.explanation}</p><div className="mt-4 flex flex-wrap gap-2">{offer.products.map((product) => <span key={product} className="rounded-full bg-white/[.05] px-2.5 py-1 text-xs text-slate-300">{product}</span>)}</div><div className="mt-5 rounded-xl bg-white/[.03] p-4"><div className="flex justify-between text-sm text-slate-400"><span>Approved offer</span><span>{money(offer.offer_price_paise)}</span></div>{offer.coupon_code && <div className="mt-2 flex justify-between text-sm text-emerald-300"><span className="flex items-center gap-1"><Ticket size={14} /> {offer.coupon_code}</span><span>−{money(offer.coupon_discount_paise)}</span></div>}<div className="mt-3 flex justify-between border-t border-white/10 pt-3 text-sm font-semibold"><span>Payable at checkout</span><span>{money(offer.final_price_paise)}</span></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><input value={customerName} onChange={(event) => onCustomerName(event.target.value)} className="rounded-lg border border-white/15 bg-slate-950 px-3 py-2 text-sm outline-none focus:border-cyan-300" placeholder="Customer name" /><input value={customerEmail} onChange={(event) => onCustomerEmail(event.target.value)} className="rounded-lg border border-white/15 bg-slate-950 px-3 py-2 text-sm outline-none focus:border-cyan-300" placeholder="Customer email" /></div><button disabled={disabled || !customerName || !customerEmail} onClick={() => void onCheckout(offer)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-cyan-200 disabled:opacity-50"><BadgeIndianRupee size={17} /> Continue to payment</button></article>;
}

function PaymentResult({ payment }: { payment: PaymentLink }) { return <section className={`rounded-2xl border p-5 ${payment.provider === "razorpay" ? "border-emerald-400/30 bg-emerald-400/10" : "border-amber-400/30 bg-amber-400/10"}`}><div className="flex gap-3"><CheckCircle2 className={payment.provider === "razorpay" ? "text-emerald-300" : "text-amber-200"} /><div><h3 className="font-semibold">{payment.provider === "razorpay" ? "Razorpay Test Mode payment link created" : "Demo checkout recorded"}</h3><p className="mt-1 text-sm text-slate-300">Amount: {money(payment.amount_paise)} · Status: {payment.status.replace("_", " ")}</p>{payment.short_url ? <a className="mt-3 inline-flex items-center gap-2 text-sm font-medium text-emerald-200 hover:text-white" href={payment.short_url} target="_blank" rel="noreferrer">Open Razorpay payment link <ExternalLink size={15} /></a> : <p className="mt-3 text-sm text-amber-100">{payment.failure_reason}</p>}</div></div></section>; }
