import { BadgeIndianRupee, CheckCircle2, ExternalLink, Search, Sparkles, Ticket, X } from "lucide-react";
import { useState } from "react";
import type { PaymentLink, ShoppingOffer, ShoppingSearchResponse } from "../types";

const money = (paise: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(paise / 100);

export function ShoppingPage({ result, searching, error, onSearch, onCheckout }: { result: ShoppingSearchResponse | null; searching: boolean; error: string | null; onSearch: (query: string, budget: string) => Promise<void>; onCheckout: (offer: ShoppingOffer, name: string, email: string) => Promise<PaymentLink | undefined> }) {
  const [query, setQuery] = useState("skincare routine with sunscreen");
  const [budget, setBudget] = useState("1500");
  const [customerName, setCustomerName] = useState("Demo Customer");
  const [customerEmail, setCustomerEmail] = useState("customer@example.com");
  const [payment, setPayment] = useState<PaymentLink | null>(null);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setPayment(null); await onSearch(query, budget); };
  const checkout = async (offer: ShoppingOffer) => { const next = await onCheckout(offer, customerName, customerEmail); if (next) setPayment(next); };
  return <div className="space-y-7"><section className="rounded-2xl border border-sky-200 bg-white p-7 shadow-sm sm:p-9"><p className="text-sm font-semibold uppercase tracking-[.18em] text-sky-600">Customer Shopping Agent</p><h2 className="mt-2 max-w-3xl text-3xl font-semibold tracking-tight">Find the best merchant-approved offer.</h2><p className="mt-3 max-w-3xl text-slate-500">Compare approved skincare, coffee, and fitness bundles. Arvya applies eligible merchant coupons before payment.</p><form onSubmit={submit} className="mt-6 grid gap-3 lg:grid-cols-[1fr_150px_auto]"><label className="sr-only" htmlFor="shopping-query">What are you looking for?</label><div className="relative"><Search size={17} className="absolute left-3 top-3 text-slate-500" /><input id="shopping-query" value={query} onChange={(event) => setQuery(event.target.value)} className="w-full rounded-lg border border-slate-200 bg-white py-2.5 pl-10 pr-3 text-sm outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100" placeholder="Try: coffee beans, gym kit, or skincare routine" /></div><input value={budget} onChange={(event) => setBudget(event.target.value)} type="number" min="1" className="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100" placeholder="Budget in ₹" /><button disabled={searching} className="rounded-lg bg-sky-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-sky-700 disabled:opacity-60">{searching ? "Comparing…" : "Compare offers"}</button></form></section>{error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{result && <><section className="rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-500 shadow-sm"><span className="font-medium text-slate-800">Agent reasoning:</span> {result.recommendation_summary}</section>{result.offers.length ? <div className="grid gap-5 xl:grid-cols-2">{result.offers.map((offer, index) => <OfferCard key={offer.recommendation_id} offer={offer} rank={index + 1} customerName={customerName} customerEmail={customerEmail} onCustomerName={setCustomerName} onCustomerEmail={setCustomerEmail} onCheckout={checkout} disabled={searching} />)}</div> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><Sparkles className="mx-auto text-sky-500" /><h3 className="mt-4 font-medium">No approved offers to compare yet</h3><p className="mt-2 text-sm text-slate-500">Try searches around skincare, coffee, or fitness. Merchants can also generate and approve additional offers.</p></div>}</>}{payment && <PaymentResult payment={payment} onClose={() => setPayment(null)} />}</div>;
}

function OfferCard({ offer, rank, customerName, customerEmail, onCustomerName, onCustomerEmail, onCheckout, disabled }: { offer: ShoppingOffer; rank: number; customerName: string; customerEmail: string; onCustomerName: (value: string) => void; onCustomerEmail: (value: string) => void; onCheckout: (offer: ShoppingOffer) => Promise<void>; disabled: boolean }) {
  return <article className={`rounded-2xl border bg-white p-6 shadow-sm ${rank === 1 ? "border-sky-300 ring-1 ring-sky-100" : "border-slate-200"}`}><div className="flex items-start justify-between gap-4"><div>{rank === 1 && <span className="rounded-full bg-sky-50 px-2.5 py-1 text-xs font-medium text-sky-700">Best match</span>}<h3 className="mt-3 text-lg font-semibold text-slate-900">{offer.title}</h3><p className="mt-1 text-sm text-slate-500">{offer.merchant_name} · {offer.merchant_industry}</p></div><div className="text-right"><p className="text-xs text-slate-500">Final price</p><p className="text-xl font-semibold text-slate-900">{money(offer.final_price_paise)}</p></div></div><p className="mt-4 text-sm leading-6 text-slate-600">{offer.explanation}</p><div className="mt-4 flex flex-wrap gap-2">{offer.products.map((product) => <span key={product} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{product}</span>)}</div><div className="mt-5 rounded-xl bg-slate-50 p-4"><div className="flex justify-between text-sm text-slate-500"><span>Approved offer</span><span>{money(offer.offer_price_paise)}</span></div>{offer.coupon_code && <div className="mt-2 flex justify-between text-sm text-emerald-600"><span className="flex items-center gap-1"><Ticket size={14} /> {offer.coupon_code}</span><span>−{money(offer.coupon_discount_paise)}</span></div>}<div className="mt-3 flex justify-between border-t border-slate-200 pt-3 text-sm font-semibold text-slate-900"><span>Payable at checkout</span><span>{money(offer.final_price_paise)}</span></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><input value={customerName} onChange={(event) => onCustomerName(event.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100" placeholder="Customer name" /><input value={customerEmail} onChange={(event) => onCustomerEmail(event.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100" placeholder="Customer email" /></div><button disabled={disabled || !customerName || !customerEmail} onClick={() => void onCheckout(offer)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-sky-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-sky-700 disabled:opacity-50"><BadgeIndianRupee size={17} /> Create payment link</button></article>;
}

function PaymentResult({ payment, onClose }: { payment: PaymentLink; onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/40 p-5"><section className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div className={`grid h-11 w-11 place-items-center rounded-full ${payment.provider === "razorpay" ? "bg-emerald-50 text-emerald-600" : "bg-amber-50 text-amber-600"}`}><CheckCircle2 /></div><button onClick={onClose} className="rounded-lg p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><X size={20} /></button></div><h3 className="mt-5 text-xl font-semibold text-slate-900">{payment.provider === "razorpay" ? "Payment link ready" : "Demo checkout created"}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{payment.provider === "razorpay" ? "Your customer can now complete payment through Razorpay Test Mode." : "The offer, coupon, and amount were validated. Add Test Mode credentials to generate a real Razorpay link."}</p><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">Amount payable</p><p className="mt-1 text-2xl font-semibold text-slate-900">{money(payment.amount_paise)}</p><p className="mt-1 text-sm text-slate-500">Status: {payment.status.replace("_", " ")}</p></div>{payment.short_url ? <a className="mt-5 flex items-center justify-center gap-2 rounded-lg bg-sky-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-sky-700" href={payment.short_url} target="_blank" rel="noreferrer">Open Razorpay Test Mode link <ExternalLink size={16} /></a> : <div className="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">{payment.failure_reason}</div>}<button onClick={onClose} className="mt-3 w-full rounded-lg px-4 py-2 text-sm font-medium text-slate-600 hover:bg-slate-100">Close</button></section></div>; }
